# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0003_auto_20181201_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='Edad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='FechaNacimiento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='Rut',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='Telefono',
            field=models.CharField(max_length=30),
        ),
    ]
