# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0004_auto_20181201_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='Domicilio',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='Region',
            field=models.CharField(default='Regi\xf3n Metropolitana de Santiago', max_length=30),
        ),
    ]
