# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopcion', '0005_auto_20181201_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='Edad',
        ),
    ]
